# Generated by Django 2.2.1 on 2019-06-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='athors',
            new_name='authors',
        ),
    ]
